### ISSUE TITLE
Respect indentation style

### ISSUE THREAD

**Issue by apopiak** [athei/gitfmt#1]
Currently `gitfmt` formats files with spaces, I would like it to respect the indentation that is used in the file.

**Comment by athei** [comment]
`gitfmt` just calls `rustfmt`. Therefore it picks up your [configuration](https://github.com/rust-lang/rustfmt#configuring-rustfmt) as if you had called it by hand. Usually that just works because most projects either use the default rust style or put a `rustfmt.toml` in their project root.

That said, if you only want to change from spaces to tabs put a `rustfmt.toml` somewhere in the directory hierarchy above the project you are formatting:
`hard_tabs = true`

**Comment by apopiak** [comment]
Thanks, I forgot about the `rustfmt.toml`.
